### ISSUE TITLE
Change the header to match my live portfolio dashautyuzh.com

### ISSUE THREAD

**Issue by dutyuzh** [dutyuzh/blog#1]
I'm starting a blog off of my portfolio. I am using the open source vuejs blog that I forked. Will link the blog in my navigation but want to have the blog to have the same look and feel as my portfolio. Please update the menu to match my current navigation but hardcode the links.

**Comment by mnevins09** [comment]
I'll take this.

**Comment by joannarogalska** [comment]
dashautyuzh.com doesn't work :(
