### ISSUE TITLE
Update progress bar color

### ISSUE THREAD

**Issue by dutyuzh** [dutyuzh/blog#16]
Create a new variable in colors (dark-grape: #421c52) and update the progress bar (pace) to use this color.

**Comment by simpslandyy** [comment]
I'd like to give this a try :)

**Comment by dutyuzh** [comment]
@simpslandyy I added in-progress label. Good luck!

**Comment by simpslandyy** [comment]
@dutyuzh - is it okay if I open a PR without images of my changes? It's a little hard to capture the progress bar. Also, where is contributers.html file?

**Comment by dutyuzh** [comment]
@simpslandyy sure, I'll pull it down and check ;)
