### ISSUE TITLE
Update footer of blog to match my live portfolio: dashautyuzh.com

### ISSUE THREAD

**Issue by dutyuzh** [dutyuzh/blog#5]
Update footer of blog to match my live portfolio: dashautyuzh.com

**Comment by masquel** [comment]
I'll take this one

**Comment by dutyuzh** [comment]
Thank you @masquel I'll put in progress label

**Comment by masquel** [comment]
@dutyuzh do you want social links and "start a project" button to copy, or only social?

**Comment by dutyuzh** [comment]
You can leave that out. Just the social icons will do :-)
