### ISSUE TITLE
Update the styles / colors on this blog to match my portfolio: http://dashautyuzh.com

### ISSUE THREAD

**Issue by dutyuzh** [dutyuzh/blog#6]
Update the h1-h5 colors to match my portfolio that's found here: http://dashautyuzh.com

**Comment by adityatandon007** [comment]
@dutyuzh I would like to pick this up

**Comment by dutyuzh** [comment]
Perfect! @adityatandon007 will add in-progress tag!

**Comment by adityatandon007** [comment]
@dutyuzh let me know in case you need to change the color.

**Comment by adityatandon007** [comment]
@dutyuzh please review
